from pdf_interaction import PDF_Interaction
import pathlib
if __name__ == "__main__":
    pdf_creator = PDF_Interaction()
    info = {
        "client_name": "John Doe",
        "sex": "Male",
        "d_o_b": "03/27/1991",
        "record_number": "03124",
        "diagnosis": "Depression",
        "precautions": "N/A",
        "contraindications": "N/A",
        "date": "03/25/2023",
        "summary": "The client experienced flashes where they were beside themselves and considered a danger to themselves and others",
        "performance": "The client is has been noticing small happiness and activities that they enjoyed as a child",
        "recommendations": "We plan to keep introducing fun activities to the client that reminds them of their childhood",
        "billing": "978145",
        "units": "2"
    }

    #pdf_creator.create_progress_pdf(info)

    info2 = {
        "name": "John Doe",
        "dob": "03/27/1991",
        "date": "03/25/2023",
        "med_num": "03124",
        "diagnosis": "Depression",
        "med_hx": "Broken legs and arms",
        "prior_lev": "Fully functioning body",
        "prior_liv": "Lives with both parents and two siblings",
        "hearing": "Hears pretty good",
        "visual_perception": "20/20",
        "AO": "A&O Value",
        "memory": "Memory Value",
        "mmse": "40",
        "blood_pressure": "80",
        "heart_rate": "120/80",
        "oxygen": "90",
        "respiratory_rate": "60",
        "pain_assessment": "Painful Value",
        "eat_init": "6",
        "eat_goal": "9",
        "d_e": "N/A",
        "groom_init": "5",
        "groom_goal": "8",
        "d_g": "N/A",
        "bath_init": "0",
        "bath_goal": "3",
        "d_b": "N/A",
        "upper_init": "2",
        "upper_goal": "4",
        "d_ubd": "N/A",
        "lower_init": "2",
        "lower_goal": "4",
        "d_lbd": "N/A",
        "toilet_init": "3",
        "toilet_goal": "5",
        "d_t": "N/A",
        "toilet_transfer_init": "3",
        "toilet_transfer_goal" : "6",
        "d_tt" : "N/A",
        "shower_transfer_init" : "7",
        "shower_transfer_goal" : "9",
        "d_st" : "N/A",
        "tub_transfer_init" : "6",
        "tub_transfer_goal": "10",
        "d_tut" : "N/A",
        "ADL" : "There were additional ADL and IADL observations during the evaluation of the patient.",
        "current_transfer" : "The client has good mobility for the current assessment of their abilities",
        "hand_dom" : "R",
        "lue_shoulder_ev_rom" : "6",
        "lue_shoulder_ev_mmt" : "7",
        "rue_shoulder_ev_rom" : "2",
        "rue_shoulder_ev_mmt" : "5",
        "lue_shoulder_flex_rom" : "1",
        "lue_shoulder_flex_mmt" : "3",
        "rue_shoulder_flex_rom" : "5",
        "rue_shoulder_flex_mmt" : "8",
        "lue_shoulder_ext_rom" : "4",
        "lue_shoulder_ext_mmt" : "6",
        "rue_shoulder_ext_rom":"9",
        "rue_shoulder_ext_mmt":"8",
        "lue_shoulder_abd_rom":"0",
        "lue_shoulder_abd_mmt":"2",
        "rue_shoulder_abd_rom":"4",
        "rue_shoulder_abd_mmt":"6",
        "lue_hor_abd_rom":"2",
        "lue_hor_abd_mmt":"3",
        "rue_hor_abd_rom":"4",
        "rue_hor_abd_mmt":"1",
        "lue_hor_add_rom":"6",
        "lue_hor_add_mmt":"7",
        "rue_hor_add_rom":"8",
        "rue_hor_add_mmt":"9",
        "lue_intern_rot_rom":"2",
        "lue_intern_rot_mmt":"3",
        "rue_intern_rot_rom":"5",
        "rue_intern_rot_mmt":"7",
        "lue_extern_rot_rom":"1",
        "lue_extern_rot_mmt":"1",
        "rue_extern_rot_rom":"3",
        "rue_extern_rot_mmt":"4",
        "lue_elbow_flex_rom":"5",
        "lue_elbow_flex_mmt":"7",
        "rue_elbow_flex_rom":"8",
        "rue_elbow_flex_mmt":"9",
        "lue_elbow_ext_rom":"8",
        "lue_elbow_ext_mmt":"7",
        "rue_elbow_ext_rom":"3",
        "rue_elbow_ext_mmt":"",
        "lue_fore_pro_rom" : "9",
        "lue_fore_pro_mmt" : "6",
        "rue_fore_pro_rom" : "4",
        "rue_fore_pro_mmt" : "2",
        "lue_fore_sup_rom":"2",
        "lue_fore_sup_mmt":"5",
        "rue_fore_sup_rom":"6",
        "rue_fore_sup_mmt":"7",
        "lue_wrist_flex_rom":"8",
        "lue_wrist_flex_mmt":"5",
        "rue_wrist_flex_rom":"3",
        "rue_wrist_flex_mmt":"2",
        "lue_wrist_ext_rom":"1",
        "lue_wrist_ext_mmt":"9",
        "rue_wrist_ext_rom":"6",
        "rue_wrist_ext_mmt":"3",
        "other_observations" : "The patient exhibits unease when speaking about familial matters.",
        "lue_grip_str" : "3",
        "rue_grip_str" : "4",
        "lue_lat_pinch" : "5",
        "rue_lat_pinch" : "6",
        "lue_tri_pinch" : "1",
        "rue_tri_pinch" : "2",
        "lue_tip_pinch" : "7",
        "rue_tip_pinch" : "9",
        "lue_light_touch" : "8",
        "rue_light_touch" : "5",
        "lue_sh_du" : "6",
        "rue_sh_du" : "4",
        "lue_temp" : "3",
        "rue_temp" : "5",
        "lue_prop" : "4",
        "rue_prop" : "3",
        "lue_ster" : "6",
        "rue_ster" : "8",
        "lue_peg" : "9",
        "rue_peg" : "2",
        "lue_edema" : "1",
        "rue_edema" : "1",
        "lue_pain" : "0",
        "rue_pain" : "7",
        "justification": "Patient had been experiencing difficulty with grip in the legs",
        "init_assess" : "The patient has difficulty holding things within their hands which leads to them dropping many objects on the floor.",
        "dis_rec" : "Follow up with therapist/doctor once a month",
        "equip_needs" : "Glove to support wrist",
        "patient_goals" : "To hold an item for minutes at a time",
        "est_len" : "3 weeks",
        "overall_goals" : "Full functionality of hands",
        "short_term_goal" : "Hold item for 15 seconds",
        "signature" : "Jane Smith",
        "date_of_sig" : "03/25/2023",
        "billing" : "978456",
        "units": "2"
    }

    #pdf_creator.create_initial_pdf(info2)

    info3 = {
        "client_name": "John Doe",
        "d_o_b": "03/27/1991",
        "date_of_eval": "03/25/2023",
        "record_number": "03124",
        "diagnosis": "Depression",
        "medical_hx": "Broken legs and arms",
        "prior_function": "Fully functioning body",
        "prior_living": "Lives with both parents and two siblings",
        "hearing": "Hears pretty good",
        "vision": "20/20",
        "a_o": "A&O Value",
        "memory": "Memory Value",
        "mmse_score": "40",
        "b_p": "80",
        "heart_rate": "120/80",
        "oxygen": "90",
        "R_R": "60",
        "pain": "Painful Value",
        "i_e": "6",
        "g_e": "9",
        "d_e": "8",
        "i_g": "5",
        "g_g": "8",
        "d_g": "7",
        "i_b": "0",
        "g_b": "3",
        "d_b": "2",
        "i_ubd": "2",
        "g_ubd": "4",
        "d_ubd": "3",
        "i_lbd": "2",
        "g_lbd": "4",
        "d_lbd": "3",
        "i_t": "3",
        "g_t": "5",
        "d_t": "4",
        "i_tt": "3",
        "g_tt" : "6",
        "d_tt" : "5",
        "i_st" : "7",
        "g_st" : "9",
        "d_st" : "8",
        "i_tut" : "6",
        "g_tut": "10",
        "d_tut" : "9",
        "adl" : "There were additional ADL and IADL observations during the evaluation of the patient.",
        "transfer" : "The client has good mobility for the discharge assessment of their abilities",
        "hand_dominance" : "R",
        "lse_r" : "6",
        "lse_m" : "7",
        "rse_r" : "2",
        "rse_m" : "5",
        "lsf_r" : "1",
        "lsf_m" : "3",
        "rsf_r" : "5",
        "rsf_m" : "8",
        "lsx_r" : "4",
        "lsx_m" : "6",
        "rsx_r" : "9",
        "rsx_m" : "8",
        "lsa_r" : "0",
        "lsa_m" : "2",
        "rsa_r" : "4",
        "rsa_m" : "6",
        "lhb_r" : "2",
        "lhb_m" : "3",
        "rhb_r" : "4",
        "rhb_m" : "1",
        "lhd_r" : "6",
        "lhd_m" : "7",
        "rhd_r" : "8",
        "rhd_m" : "9",
        "lir_r" : "2",
        "lir_m" : "3",
        "rir_r" : "5",
        "rir_m" : "7",
        "ler_r" : "1",
        "ler_m" : "1",
        "rer_r" : "3",
        "rer_m" : "4",
        "lef_r" : "5",
        "lef_m" : "7",
        "ref_r" : "8",
        "ref_m" : "9",
        "lee_r" : "3",
        "lee_m" : "2",
        "ree_r" : "1",
        "ree_m" : "7",
        "lfp_r" : "9",
        "lfp_m" : "6",
        "rfp_r" : "4",
        "rfp_m" : "2",
        "lfs_r" : "2",
        "lfs_m" : "5",
        "rfs_r" : "6",
        "rfs_m" : "7",
        "lwf_r" : "8",
        "lwf_m" : "5",
        "rwf_r" : "3",
        "rwf_m" : "2",
        "lwe_r" : "1",
        "lwe_m" : "9",
        "rwe_r" : "6",
        "rwe_m" : "3",
        "other_observations" : "The patient exhibits unease when speaking about familial matters.",
        "l_gs" : "3",
        "r_gs" : "4",
        "l_lp" : "5",
        "r_lp" : "6",
        "l_trp" : "1",
        "r_trp" : "2",
        "l_tp" : "7",
        "r_tp" : "9",
        "l_lt" : "8",
        "r_lt" : "5",
        "l_sd" : "6",
        "r_sd" : "4",
        "l_t" : "3",
        "r_t" : "5",
        "l_pro" : "4",
        "r_pro" : "3",
        "l_ste" : "6",
        "r_ste" : "8",
        "l_9h" : "9",
        "r_9h" : "2",
        "l_ed" : "1",
        "r_ed" : "1",
        "l_pain" : "0",
        "r_pain" : "7",
        "assessment_problems" : "The patient has difficulty holding things within their hands which leads to them dropping many objects on the floor.",
        "discharge_recommendation" : "Follow up with therapist/doctor once a month",
        "equipment_needs" : "Glove to support wrist",
        "patient_goals" : "To hold an item for minutes at a time",
        "rehab" : "Do wrist exercises 2-3 times a week for an hour",
        "referral" : "Refer to Dr. Harrington for further checkups",
        "education" : "B.S. Iona University",
        "signature" : "Jane Smith",
        "date" : "03/25/2023",
        "billing_code" : "978456",
        "units": "2"
    }

    #pdf_creator.create_discharge_pdf(info3)
    
    #print(pathlib.Path.home() / "Downloads" / "new_folder" / "eval.pdf")