from pdf_interaction import PDF_Interaction

if __name__ == "__main__":
    pdf_creator = PDF_Interaction()
    info = {
        "name": "John Doe",
        "sex": "Male",
        "DOB": "03/27/1991",
        "record_number": "03124",
        "diagnosis": "Depression",
        "precautions": "N/A",
        "contraindications": "N/A",
        "date": "03/25/2023",
        "summaryOfServices": "The client experienced flashes where they were beside themselves and considered a danger to themselves and others",
        "performance": "The client is has been noticing small happiness and activities that they enjoyed as a child",
        "planOrReccomendations": "We plan to keep introducing fun activities to the client that reminds them of their childhood",
        "billing": "978145",
        "units": "2"
    }

    #pdf_creator.create_progress_pdf(info)

    info2 = {
        "name": "John Doe",
        "dob": "03/27/1991",
        "date": "03/25/2023",
        "med_num": "03124",
        "diagnosis": "Depression",
        "med_hx": "Broken legs and arms",
        "prior_lev": "Fully functioning body",
        "prior_liv": "Lives with both parents and two siblings",
        "hearing": "Hears pretty good",
        "visual_perception": "20/20",
        "AO": "A&O Value",
        "memory": "Memory Value",
        "mmse": "40",
        "blood_pressure": "80",
        "heart_rate": "120/80",
        "oxygen": "90",
        "respiratory_rate": "60",
        "pain_assessment": "Painful Value",
        "eat_init": "6",
        "eat_goal": "9",
        "d_e": "N/A",
        "groom_init": "5",
        "groom_goal": "8",
        "d_g": "N/A",
        "bath_init": "0",
        "bath_goal": "3",
        "d_b": "N/A",
        "upper_init": "2",
        "upper_goal": "4",
        "d_ubd": "N/A",
        "lower_init": "2",
        "lower_goal": "4",
        "d_lbd": "N/A",
        "toilet_init": "3",
        "toilet_goal": "5",
        "d_t": "N/A",
        "toilet_transfer_init": "3",
        "toilet_transfer_goal" : "6",
        "d_tt" : "N/A",
        "shower_transfer_init" : "7",
        "shower_transfer_goal" : "9",
        "d_st" : "N/A",
        "tub_transfer_init" : "6",
        "tub_transfer_goal": "10",
        "d_tut" : "N/A",
        "ADL" : "There were additional ADL and IADL observations during the evaluation of the patient.",
        "current_transfer" : "The client has good mobility for the current assessment of their abilities",
        "hand_dom" : "R",
        "lue_shoulder_ev_rom" : "6",
        "lue_shoulder_ev_mmt" : "7",
        "rue_shoulder_ev_rom" : "2",
        "rue_shoulder_ev_mmt" : "5",
        "lue_shoulder_flex_rom" : "1",
        "lue_shoulder_flex_mmt" : "3",
        "rue_shoulder_flex_rom" : "5",
        "rue_shoulder_flex_mmt" : "8",
        "lue_shoulder_ext_rom" : "4",
        "lue_shoulder_ext_mmt" : "6",
        "rue_shoulder_ext_rom":"9",
        "rue_shoulder_ext_mmt":"8",
        "lue_shoulder_abd_rom":"0",
        "lue_shoulder_abd_mmt":"2",
        "rue_shoulder_abd_rom":"4",
        "rue_shoulder_abd_mmt":"6",
        "lue_hor_abd_rom":"2",
        "lue_hor_abd_mmt":"3",
        "rue_hor_abd_rom":"4",
        "rue_hor_abd_mmt":"1",
        "lue_hor_add_rom":"6",
        "lue_hor_add_mmt":"7",
        "rue_hor_add_rom":"8",
        "rue_hor_add_mmt":"9",
        "lue_intern_rot_rom":"2",
        "lue_intern_rot_mmt":"3",
        "rue_intern_rot_rom":"5",
        "rue_intern_rot_mmt":"7",
        "lue_extern_rot_rom":"1",
        "lue_extern_rot_mmt":"1",
        "rue_extern_rot_rom":"3",
        "rue_extern_rot_mmt":"4",
        "lue_elbow_flex_rom":"5",
        "lue_elbow_flex_mmt":"7",
        "rue_elbow_flex_rom":"8",
        "rue_elbow_flex_mmt":"9",
        "lue_elbow_ext_rom":"8",
        "lue_elbow_ext_mmt":"7",
        "rue_elbow_ext_rom":"3",
        "rue_elbow_ext_mmt":"",
        "lue_fore_pro_rom" : "9",
        "lue_fore_pro_mmt" : "6",
        "rue_fore_pro_rom" : "4",
        "rue_fore_pro_mmt" : "2",
        "lue_fore_sup_rom":"2",
        "lue_fore_sup_mmt":"5",
        "rue_fore_sup_rom":"6",
        "rue_fore_sup_mmt":"7",
        "lue_wrist_flex_rom":"8",
        "lue_wrist_flex_mmt":"5",
        "rue_wrist_flex_rom":"3",
        "rue_wrist_flex_mmt":"2",
        "lue_wrist_ext_rom":"1",
        "lue_wrist_ext_mmt":"9",
        "rue_wrist_ext_rom":"6",
        "rue_wrist_ext_mmt":"3",
        "other_observations" : "The patient exhibits unease when speaking about familial matters.",
        "lue_grip_str" : "3",
        "rue_grip_str" : "4",
        "lue_lat_pinch" : "5",
        "rue_lat_pinch" : "6",
        "lue_tri_pinch" : "1",
        "rue_tri_pinch" : "2",
        "lue_tip_pinch" : "7",
        "rue_tip_pinch" : "9",
        "lue_light_touch" : "8",
        "rue_light_touch" : "5",
        "lue_sh_du" : "6",
        "rue_sh_du" : "4",
        "lue_temp" : "3",
        "rue_temp" : "5",
        "lue_prop" : "4",
        "rue_prop" : "3",
        "lue_ster" : "6",
        "rue_ster" : "8",
        "lue_peg" : "9",
        "rue_peg" : "2",
        "lue_edema" : "1",
        "rue_edema" : "1",
        "lue_pain" : "0",
        "rue_pain" : "7",
        "justification": "Patient had been experiencing difficulty with grip in the legs",
        "init_assess" : "The patient has difficulty holding things within their hands which leads to them dropping many objects on the floor.",
        "dis_rec" : "Follow up with therapist/doctor once a month",
        "equip_needs" : "Glove to support wrist",
        "patient_goals" : "To hold an item for minutes at a time",
        "est_len" : "3 weeks",
        "overall_goals" : "Full functionality of hands",
        "short_term_goal" : "Hold item for 15 seconds",
        "signature" : "Jane Smith",
        "date_of_sig" : "03/25/2023",
        "billing" : "978456",
        "units": "2"
    }

    #pdf_creator.create_initial_pdf(info2)

    info3 = {
        "name": "Cameron Deshnad",
        "sex": "Male",
        "dob": "06/04/1955",
        "date": "04/16/2023",
        "med_num": "57894",
        "med_hx": "Prior issues with his legs and allergy to peanuts.",
        "diagnosis": "Struggles to remember daily tasks and that is affecting his relationship with his family members.",
        "prior_lev": "Fully functioning memory and body until 1980.",
        "prior_liv": "Was with his wife but now only visited by his children a couple times of the week.",
        "hearing": "Fully functioning hearing.",
        "visual_perception": "Fully functioning vision.",
        "AO": "X3",
        "memory": "Poor memory but good cognition.",
        "mmse": "87",
        "blood_pressure": "120",
        "heart_rate": "67",
        "oxygen": "68",
        "respiratory_rate": "543",
        "pain_assessment": "45",
        "eat_init": "3",
        "eat_goal": "5",
        "eat_disc": "7",
        "groom_init": "4",
        "groom_goal": "6",
        "groom_disc": "8",
        "bath_init": "3",
        "bath_goal": "5",
        "bath_disc": "7",
        "upper_init": "2",
        "upper_goal": "9",
        "upper_disc": "9",
        "lower_init": "3",
        "lower_goal": "8",
        "lower_disc": "5",
        "toilet_init": "2",
        "toilet_goal": "9",
        "toilet_disc": "3",
        "toilet_transfer_init": "1",
        "toilet_transfer_goal": "4",
        "toilet_transfer_disc": "6",
        "shower_transfer_init": "4",
        "shower_transfer_goal": "6",
        "shower_transfer_disc": "9",
        "tub_transfer_init": "5",
        "tub_transfer_goal": "8",
        "tub_transfer_disc": "3",
        "hand_dom": "Right",
        "lue_shoulder_ev_rom": "3",
        "lue_shoulder_ev_mmt": "5",
        "rue_shoulder_ev_rom": "8",
        "rue_shoulder_ev_mmt": "4",
        "lue_shoulder_flex_rom": "9",
        "lue_shoulder_flex_mmt": "5",
        "rue_shoulder_flex_rom": "3",
        "rue_shoulder_flex_mmt": "7",
        "lue_shoulder_ext_rom": "3",
        "lue_shoulder_ext_mmt": "5",
        "rue_shoulder_ext_rom": "8",
        "rue_shoulder_ext_mmt": "3",
        "lue_shoulder_abd_rom": "6",
        "lue_shoulder_abd_mmt": "5",
        "rue_shoulder_abd_rom": "8",
        "rue_shoulder_abd_mmt": "5",
        "lue_hor_abd_rom": "5",
        "lue_hor_abd_mmt": "7",
        "rue_hor_abd_rom": "8",
        "rue_hor_abd_mmt": "4",
        "lue_hor_add_rom": "6",
        "lue_hor_add_mmt": "8",
        "rue_hor_add_rom": "9",
        "rue_hor_add_mmt": "1",
        "lue_intern_rot_rom": "4",
        "lue_intern_rot_mmt": "6",
        "rue_intern_rot_rom": "8",
        "rue_intern_rot_mmt": "5",
        "lue_extern_rot_rom": "3",
        "lue_extern_rot_mmt": "8",
        "rue_extern_rot_rom": "5",
        "rue_extern_rot_mmt": "6",
        "lue_elbow_flex_rom": "2",
        "lue_elbow_flex_mmt": "7",
        "rue_elbow_flex_rom": "9",
        "rue_elbow_flex_mmt": "5",
        "lue_elbow_ext_rom": "7",
        "lue_elbow_ext_mmt": "8",
        "rue_elbow_ext_rom": "3",
        "rue_elbow_ext_mmt": "6",
        "lue_fore_pro_rom": "2",
        "lue_fore_pro_mmt": "4",
        "rue_fore_pro_rom": "7",
        "rue_fore_pro_mmt": "8",
        "lue_fore_sup_rom": "9",
        "lue_fore_sup_mmt": "3",
        "rue_fore_sup_rom": "5",
        "rue_fore_sup_mmt": "2",
        "lue_wrist_flex_rom": "6",
        "lue_wrist_flex_mmt": "8",
        "rue_wrist_flex_rom": "3",
        "rue_wrist_flex_mmt": "4",
        "lue_wrist_ext_rom": "8",
        "lue_wrist_ext_mmt": "6",
        "rue_wrist_ext_rom": "2",
        "rue_wrist_ext_mmt": "5",
        "lue_grip_str": "7",
        "rue_grip_str": "8",
        "lue_lat_pinch": "4",
        "rue_lat_pinch": "9",
        "lue_tri_pinch": "2",
        "rue_tri_pinch": "7",
        "lue_tip_pinch": "8",
        "rue_tip_pinch": "4",
        "lue_light_touch": "3",
        "rue_light_touch": "5",
        "lue_sh_du": "8",
        "rue_sh_du": "4",
        "lue_temp": "9",
        "rue_temp": "4",
        "lue_prop": "5",
        "rue_prop": "6",
        "lue_ster": "2",
        "rue_ster": "1",
        "lue_peg": "4",
        "rue_peg": "8",
        "lue_edema": "5",
        "rue_edema": "4",
        "lue_pain": "9",
        "rue_pain": "8",
        "ADL": "N/A",
        "current_transfer": "Performs various movement tasks with good efficiency.",
        "disc_assess": "Strengths:\nPerforms better with remembering names\nProblems:\nDoesn't do great with remembering faces",
        "observations": "N/A",
        "equip_needs": "N/A",
        "dis_rec": "Repetitions in remembering his family members.",
        "patient_goals": "To remember one side of the family entirely and then the other",
        "discharge_recommendations_referrals": "See Dr. Williams and Dr. Sawh",
        "client_education": "Bachelor Degree from Iona University",
        "course_of_rehab": "N/A",
        "justification": "OTC methods proved unsuccessful",
        "billing": "97110",
        "units": "2",
        "signature": "Elijah Williams",
        "date_of_sig": "04/16/2023"
    }

    #pdf_creator.create_discharge_pdf(info3)
